---
- hosts: all

  tasks:
    - name: judge file is exits
      stat: path=/opt/block.txt
      ignore_errors: True
      register: file_result

    - debug:
        msg: "the block.txt not exists"
      when: file_result.stat.exists != True
    - debug:
        msg: "the block.txt is exists"
      when: file_result.stat.exists != False


    - name: the block.txt is not exists and create the file
      file: path=/opt/block.txt state=touch mode=0777
      when: file_result.stat.exists != True


    - name: cat /opt/block.txt
      shell : cat /opt/block.txt
      register: result
    - debug:
        msg: "{{ result.stdout_lines }}"
      ignore_errors: yes

    - name: delete the block1
      lineinfile:
        dest: /opt/block.txt
        regexp: '^{{item}}'
        state: absent
      with_items:
        - b*
        - "ANSIBLE INJECTED  NODE SSH FOR"



    - name: insert lineinfile in file
      blockinfile:
        dest: /opt/block.txt
        state: present
        marker: "ANSIBLE INJECTED  NODE SSH FOR"
        block: |
          block1
          block2
          block3
#      run_once: yes
