#1.同步阻塞模式指在playbook执行时，控制端和被控制端会一直保持连接状态，逐个任务的执行，直到该playbook执行完毕，这种模式称为同步阻塞模式，也是absible的默认执行模式
#2.异步模式指ansible将一次性运行所有的任务，并将所有的任务丢到后台执行，每个任务有一个job_id，ansible会根据这个job_id每隔一段时间轮训检测该任务的执行情况，直到检测到任务执行结束。这种模式称为异步模式

---
- hosts: all
#forks 并发数默认是5个，可以在ansible.cfg中设置
  serial: 3
  tasks:
    - name: serial用于控制一个play内的主机并行数，这个并行数不能超过forks，超过后则serial不会生效
      shell:
        cmd: sleep 10
#async和poll分别用来指定异步模式下任务的最大运行时间和检测间隔时间，poll的缺省值为10
      async: 25
      poll: 2

#示例中sleep命令采用异步的方式执行，ansible会等待该任务最长25秒，每隔2秒钟检测一次任务的执行结果
#特殊情况下，我们可以将poll的值设置为0，这代表ansible将任务放到后台后，不会再管这个任务的执行状态，任其自生自灭


