---
- hosts:
    tasks:

    - name: backup the chrony.conf
      shell: |
        pushd /etc/
        [ -e chrony.conf ] && cp chrony.conf{,.bk}
        popd
    - debug:
        msg: "backup the chrony.conf"

    - name: mkdir /opt/rc_dir
      shell: |
        mkdir /opt/rc_dir
      register: result_rc
      fail_when: result_rc.rc != 0
    - debug:
        msg: "{{ result_rc.stdout }}"
