---
- hosts: nodes
  tasks:

#使用meta模块，headlers会在它所对应的task任务执行完后立即被触发并执行，即在playbook的中间环节运行
#默认情况下，所有的task执行完毕后，才会执行各个handles，并不是执行完某个task后，立即执行相应的handler，如果想要在执行完某些task以后立即执行对应的handlre，那么需要使用meta模块

    - name: create file1
      file: path=/opt/file1 state=directory
      notify: change mode1
    - debug:
        msg: "create file1"

    - name: create file2
      file: path=/opt/file2 state=directory
      notify: change mode2
    - meta: flush_handlers
    - debug:
        msg: "create file2"

    - name: create file3
      file: path=/opt/file3 state=directory
      notify: change mode3
    - debug:
        msg: "create file3"
    - name: create file4
      file: path=/opt/file4 state=directory
      notify: change mode4
    - debug:
        msg: "create file4"
  handlers:
    - name: change mode1
      file: path=/opt/file1/file1.txt state=touch mode=777 owner=root group=root

    - name: change mode2
      file: path=/opt/file2/file2.txt state=touch mode=777 owner=root group=root

    - name: change mode3
      file: path=/opt/file3/file3.txt state=touch mode=777 owner=root group=root

    - name: change mode4
      file: path=/opt/file4/file4.txt state=touch mode=777 owner=root group=root


#使用listen关键字，在一个tasks任务中一次性notify多个handler
#怎么才能一次性notify多个handler呢？如果尝试将多个handler使用相同的name呢？其实这样并不可行！因为当多个handler的name相同时，只有一个handler会被执行。
#要想实现一次notify多个handler，需要借助一个关键字，它就是"listen"，可以把listen理解成"组名",可以把多个handler分成"组"，当需要一次性notify多个handler时，
#只要将多个handler分为"一组"，使用相同的"组名"即可，当notify对应的值为"组名"时，"组"内的所有handler都会被notify。需要注意：listen的名称要和notify名称保持一致！

---
- hosts: nodes
  tasks:
    - name: create file1
      file: path=/opt/file1 state=directory
      notify: group_handlers1
    - meta: flush_handlers
    - debug:
        msg: "create file1"

    - name: create file2
      file: path=/opt/file2 state=directory
    - debug:
        msg: "create file2"

    - name: create file3
      file: path=/opt/file3 state=directory
    - debug:
        msg: "create file3"
    - name: create file4
      file: path=/opt/file4 state=directory
    - debug:
        msg: "create file4"

  handlers:
    - name: task1
      listen: group_handlers1
      file: path=/opt/file1/file1.txt state=touch mode=777 owner=root group=root

    - name: task2
      listen: group_handlers1
      file: path=/opt/file1/file2.txt state=touch mode=777 owner=root group=root

    - name: task3
      listen: group_handlers1
      file: path=/opt/file1/file3.txt state=touch mode=777 owner=root group=root

    - name: task4
      listen: group_handlers1
      file: path=/opt/file1/file4.txt state=touch mode=777 owner=root group=root