---
- hosts: all
  tasks:

  - name: check timezone
    shell: timedatectl  |grep "Time zone" |awk '{print $3}'
    register: timezone_result
  - debug:
#      var: timezone_result.stdout
#      var: timezone_result.cmd
#      var: timezone_result['stdout']
#      msg: " {{ timezone_result.stdout }}"
      msg: " {{ timezone_result['stdout'] }}"
    ignore_errors: yes
  #    msg: "Print the timezone is {{ timezone_result.stdout }}"
  #    ignore_errors: yes
  #
