---
- name: get dir install
  shell: pwd
  register: install_dir
- name: install rpm
  yum: name=files/hycloud-1.0.0-1.el7.centos.x86_64.rpm state=present
- name: config hycloud
  lineinfile: dest=/etc/hycloud/hycloud.conf regexp={{ item.regexp }} line={{ item.line }}
  with_item:
    - { regexp: '^conf', line: 'conf={{ install_dir.out }}' }
