---
    - name: register hosts
      set_fact:
        hosts: "{{ groups.nodes| unique | list }}"
#如果多个组可以如下添加方式
#        hosts: "{{ groups.tomcat + groups.redis + groups.nginx + groups.mysql + groups.Rabbitmq | unique | list }}"
##/etc/hosts 中添加本机的ip和主机名称对应表

    - name: change name
      shell: hostnamectl set-hostname {{inventory_hostname}}

#    - name: change /etc/hosts
#      lineinfile:
#        dest: /etc/hosts
#        line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
#    - debug:
#        msg: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"


##/etc/hosts 中添加组的的ip和主机名称对应表
    - name: set /etc/hosts all ip and hostname
      lineinfile:
        dest: /etc/hosts
        regexp: '^{{ hostvars[item].ansible_host }}'
        state: absent
        line: |
          {{ hostvars[item].ansible_host }} {{ item }}
#可以这样写
#        line: "{{ hostvars[item].ansible_host }} {{ item }}"
      with_items: "{{ hosts }}"
