---
- name: check timezone
  shell: timedatectl  |grep "Time zone" |awk '{print $3}'
  register: timezone_result
- debug:
    var: timezone_result.stdout
    msg: "The," timezone_result.stdout
  when: timezone_result.stdout !== "Asia/Shanghai"

- name: change timezone for "Asia/Shanghai"
  shell: timedatectl set-timezone Asia/Shanghai
  when: timezone_result.stdout !== "Asia/Shanghai"

- name: stop networkmager
  service: name=NetworkManager state=stopped enabled=no

- name: Check if firewalld is installed
  stat: path=/usr/lib/systemd/system/firewalld.service
  register: fw_file

- name: change sshd
  shell: sed -i -e 's/.*UseDNS.*/UseDNS no/g' -e 's/.*GSSAPIAuthentication.*/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
  notify: restart sshd service

- name: Disable firewalled if it is installed
  service: name=firewalld.service state=stopped enabled=no
  when: fw_file.stat.exists != False

- name: Update selinux config to Disabled mode
  selinux: policy=targeted state=disabled
