模板templates
文件文件，嵌套有脚本(使用模板变成语言编写)
Jinja2语言，使用字面量，有下面形式
字符串：使用单引号或双引号
数字：整数，浮点数
列表：[item1,item2,...]
元组：(item1,item2,...)
字典：{key1:value1,key2:value2,...}
布尔值：true/false
算术运算：+,-,*,/,//,%,**
比较操作：==,!=,>,>=,<,<=
逻辑运算：and,or,not
流表达式：For If When

